In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('dataset_Facebook.csv', sep=';')
df.head()

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393

In [4]:
op1=df.loc[0:50, ['Type', 'Post Weekday', 'Post Hour','like', 'share']]

In [6]:
op3=df[df['Post Hour']>3]

In [9]:
op1=op1.sort_values(by=['like', 'share'], ascending=False)
op1

      Type  Post Weekday  Post Hour    like  share
3    Photo             2         10  1572.0  147.0
17   Photo             2         12   678.0   20.0
14   Photo             4          5   577.0   20.0
28   Photo             5          3   523.0   63.0
26  Status             5         11   412.0   72.0
4    Photo             2          3   325.0   49.0
7    Photo             7          9   325.0   14.0
6    Photo             1          3   249.0   27.0
10  Status             5         10   233.0   19.0
38  Status             7          9   227.0   31.0
40  Status             6         11   216.0   39.0
41    Link             6          3   187.0   18.0
46  Status             3         11   174.0   36.0
35   Photo             1         11   172.0   21.0
8   Status             7          3   161.0   31.0
32   Photo             3          3   155.0   47.0
5   Status             1          9   152.0   33.0
29   Video             4         11   143.0   13.0
13   Photo             5          3   137.0   10.0
1   Status             3         10   130.0   29.0
9    Photo             6         10   113.0   26.0
30   Photo             4          2   107.0   22.0
27   Photo             5          3   100.0   17.0
24  Status             6         10    99.0   19.0
33   Photo             2          9    98.0   23.0
36   Photo             1          3    96.0   17.0
12   Photo             5         10    90.0   14.0
11   Photo             5         10    88.0   18.0
25  Status             6          3    88.0   18.0
15  Status             3         10    86.0   18.0
0    Photo             4          3    79.0   17.0
48   Photo             2         11    77.0   15.0
37   Photo             7         10    76.0    8.0
23   Photo             7          3    72.0   24.0
2    Photo             3          3    66.0   14.0
20   Photo             1          3    66.0   12.0
45    Link             4          3    57.0   10.0
34   Photo             2          3    56.0   17.0
18  Status             2          3    54.0   17.0
50   Photo             1          9    48.0    9.0
44   Photo             4         11    47.0   11.0
39   Photo             7          3    44.0   14.0
16   Photo             3          3    40.0   12.0
19   Photo             1         11    34.0    8.0
43    Link             5          3    29.0   10.0
31   Photo             3         10    27.0   11.0
42   Photo             5         10    26.0    3.0
47    Link             3          2    18.0    8.0
22    Link             7         10    16.0    2.0
49    Link             2          2    12.0    1.0
21   Photo             7         10     0.0    0.0

In [ ]:
df_subset1=df.loc[0:4, ['Post Month', 'comment', 'like', 'share']]
df_subset1.head()

In [ ]:
df_subset2=df.iloc[5:10, [3, 4, 5, 6, 7]]
df_subset2.head()

In [ ]:
df_subset3=df['like'].div(df['share']).to_frame('like-share-ratio')
df_subset3.head()

In [ ]:
df_merged=pd.merge(df, df_subset3, left_index=True, right_index=True)
df_merged.head()

In [ ]:
df_sorted=df.sort_values(by=['Page total likes', 'comment', 'like'], ascending=False)
df_sorted.head()

In [ ]:
df_shape=df.shape
print(df_shape)

In [ ]:
df_reshape=df.pivot(columns='Type', values='like')
df_reshape.tail()